version: '3.7'
services:
  service1: 
    image: phage2022/service1
    build: ./service1
    ports: 
    - target: 5000
      published: 5000
      protocol: tcp 
  service2: 
    image: phage2022/service2
    build: ./service2
    ports: 
    - target: 5001
      protocol: tcp 
  service3: 
   image: phage2022/service3
   build: ./service3
   ports: 
    - target: 5002
      protocol: tcp 
  service4: 
    image: phage2022/service4
    build: ./service4
    ports: 
    - target: 5003
      protocol: tcp 
  

