version: '3.7'
services:
  service1: 
  build: ./service1 
  image: practical-project/service1
  deploy:
          replicas: 4
  ports:
   - target:5000
  published: 5000
  protocol: tcp 
  

  service2:
    build: ./service2
    image: practical-project/service2
    deploy:
          replicas: 4
    ports:
    - target:5001
    published: 5001
    protocol: tcp 
    
  service3:
    build: ./service3
    image: practical-project/service3
    deploy:
          replicas: 4
    ports:
    - target:5002
    published: 5002
    
    protocol: tcp 
    
  service4:
    build: ./service4
    image: practical-project/service4
    deploy:
          replicas: 4
    ports:
    - target:5003
    published: 5003
   
    protocol: tcp 
    
