version: '3.7'
services:
  service1: 
  build: ./service1 #folder
  image: practical-project/service1
  deploy:
          replicas: 4
  ports:
   - target:5000
  published: 5000
  protocol: tcp 
  

  service2:
    build: ./service2
    image: practical-project/service2
    deploy:
          replicas: 4
    ports:
    - target:5001
    # dont need to published port cuz u dont want user to use this port
    protocol: tcp 

  service3:
    build: ./service3
    image: practical-project/service3
    deploy:
          replicas: 4
    ports:
    - target:5002
    # dont need to published port cuz u dont want user to use this port
    protocol: tcp 


  service4:
    build: ./service4
    image: practical-project/service4
    deploy:
          replicas: 4
    ports:
    - target:5003
    # dont need to published port cuz u dont want user to use this port
    protocol: tcp 

  
    
