version: '3.7'
services:
  service1: 
  build: ./service1
  image: mini-project/service1
  deploy:
          replicas: 4
  ports:
   - target:5000
  published: 5000
  

  service2:
    build: ./service2
    image: mini-project/service2
    deploy:
          replicas: 4
    ports:
    - target:5001
    published: 5001
    
