
- hosts: all
  become: yes
  roles:
  - common

- name: Setup manager
  hosts: swarm-managers
  become: yes
  roles:
  - manager

- name: Setup workers
  hosts: swarm-workers
  become: yes
  roles:
  - worker 
