- name: "clone git" 
  git:
    repo: https://github.com/PhillipHage202/practical-project.git
    dest: /home/practical-project
    update: yes

- name: "make the swarm"
  docker_swarm:
    state: present

- name: "Get swarm info"
  docker_swarm_info:
  register: swarm_info
       
- name: "Get a join token"
  add_host:
    name: "token"
    value: "{{ swarm_info['swarm_facts']['JoinTokens']['worker'] }}"